/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algo;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appHasAGreeting() {
    int x = 3;
    System.out.println(x);
    assertTrue(true);
  }
}
